export enum Specialization {
  GENERAL = 'GENERAL',
  CARDIOLOGY = 'CARDIOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  DERMATOLOGY = 'DERMATOLOGY',
  ENDOCRINOLOGY = 'ENDOCRINOLOGY',
  RADIOLOGY = 'RADIOLOGY',
  OPHTHAMOLOGY = 'OPHTHAMOLOGY',
  DENTISTRY = 'DENTISTRY',
}
